---

- name: Provisioning aws
  hosts: aws
  become: true
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.apache
    - geerlingguy.php # After geerlingguy.apache
    - geerlingguy.apache-php-fpm
    - geerlingguy.composer
    - geerlingguy.nodejs
  tasks:
     - name: Update apt
       apt:
         update_cache: yes
         cache_valid_time: 604700 # 7 days
     - name: Install unzip
       apt:
         name: unzip
         state: present
     - file:
        path: /var/www
        owner: ubuntu
        group: ubuntu
