# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.service.clean_url_generator:
        class: AppBundle\Services\CleanURLGenerator

    app.router.tag:
        class: AppBundle\Router\TagLoader
        arguments:
            - '%tags%'
            - '%locales%'
            - '@translator.default'
            - '@app.service.clean_url_generator'
        tags:
            - { name: routing.loader }

    app.twig_extension.locale_switcher:
        class: AppBundle\Twig\LocaleSwitcherExtension
        public: false
        arguments:
            - '%locales%'
        tags:
            - { name: twig.extension }

    app.twig_extension.newline_to_paragraph:
        class: AppBundle\Twig\TextToHTMLExtension
        public: false
        tags:
            - { name: twig.extension }
